
services:

  ming-m:
    build: ./mosquitto
    restart: unless-stopped
    image: ming-mosquitto
    container_name: ming-mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - ming-network
    volumes:
      - ming-m-config:/mosquitto/config:rw
      - ming-m-data:/mosquitto/data:rw
      - ming-m-log:/mosquitto/log:rw
    environment:
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME:-admin}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD:-password}

  ming-i:
    image: influxdb:latest
    container_name: ming-influxdb
    hostname: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - ming-network
    volumes:
      - ming-i-data:/var/lib/influxdb2
      - ming-i-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME:-admin}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD:-password}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG:-demo}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET:-demo}
      DOCKER_INFLUXDB_INIT_RETENTION: ${DOCKER_INFLUXDB_INIT_RETENTION:-0}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-demo}

  ming-n:
    build: ./node-red
    restart: unless-stopped
    container_name: ming-nodered
    hostname: nodered
    ports:
      - 1880:1880
    networks:
      - ming-network
    volumes:
      - ming-n-data:/data
    environment:
      TZ: ${TIMEZONE}
      NODE_RED_USERNAME: ${NODE_RED_USERNAME:-admin}
      NODE_RED_PASSWORD: ${NODE_RED_PASSWORD:-password}

  ming-g:
    image: grafana/grafana:latest
    container_name: ming-grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    networks:
      - ming-network
    volumes:
      - ming-g-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-password}
      GF_USERS_ALLOW_SIGN_UP: "false"

  ming-t:
    build: ./telegraf
    container_name: ming-telegraf
    hostname: telegraf
    networks:
      - ming-network
    volumes:
      - ming-t-config:/etc/telegraf:ro
    environment:
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG:-demo}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET:-demo}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-demo}
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME:-admin}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD:-password}
      TELEGRAF_TOPIC: ${TELEGRAF_TOPIC:-telegraf/ingest/#}
    depends_on: 
      - ming-m
      - ming-i

volumes:
  ming-m-data:
  ming-m-config:
  ming-m-log:
  ming-i-data:
  ming-i-config:
  ming-n-data:
  ming-g-data:
  ming-t-config:

networks:
  ming-network:
